#!/usr/bin/env python
"""Restore a PostgreSQL backup generated by backup_postgres.py."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse


def parse_database_url(url: str):
    parsed = urlparse(url)
    if parsed.scheme not in {"postgresql", "postgres", "postgresql+psycopg"}:
        raise ValueError("DATABASE_URL must be a PostgreSQL URL")

    return {
        "host": parsed.hostname or "localhost",
        "port": str(parsed.port or 5432),
        "user": parsed.username or "postgres",
        "password": parsed.password or "",
        "database": (parsed.path or "/").lstrip("/") or "postgres",
    }


def choose_backup_file(path_value: str) -> Path:
    path = Path(path_value)
    if path.is_file():
        return path

    if not path.exists() or not path.is_dir():
        raise FileNotFoundError(f"Backup path not found: {path}")

    candidates = sorted(path.glob("*.dump"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        raise FileNotFoundError(f"No .dump files found in directory: {path}")

    return candidates[0]


def build_restore_command(conn: dict, backup_file: Path):
    return [
        "pg_restore",
        "--clean",
        "--if-exists",
        "--no-owner",
        "--no-privileges",
        f"--host={conn['host']}",
        f"--port={conn['port']}",
        f"--username={conn['user']}",
        f"--dbname={conn['database']}",
        str(backup_file),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Restore a GestorMEI PostgreSQL backup")
    parser.add_argument(
        "backup_path",
        help="Backup file (.dump) or directory containing .dump files (latest will be used)",
    )
    args = parser.parse_args()

    database_url = os.getenv("DATABASE_URL", "")
    if not database_url:
        print("DATABASE_URL is not set.")
        return 1

    try:
        conn = parse_database_url(database_url)
        backup_file = choose_backup_file(args.backup_path)
    except (ValueError, FileNotFoundError) as exc:
        print(str(exc))
        return 1

    command = build_restore_command(conn, backup_file)
    env = os.environ.copy()
    env["PGPASSWORD"] = conn["password"]

    try:
        subprocess.run(command, check=True, env=env)
    except FileNotFoundError:
        print("pg_restore not found. Install PostgreSQL client tools and try again.")
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"Restore failed with exit code {exc.returncode}")
        return exc.returncode

    print(f"Restore completed successfully from: {backup_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
